version: "3.5"

services:
  store-service:
    image: toy-store-service:0.0.1
    container_name: store-service
    build:
      context: store-service
    ports:
      - "8000:8000"
    depends_on:
      - store-database
    restart: always

  store-database:
    image: mysql:5.7
    container_name: store-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sealteam
      - MYSQL_PASSWORD=sckshuhari
      - MYSQL_DATABASE=toy
    volumes:
      - ./tearup/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  store-web:
    image:  toy-store-web:0.0.1
    container_name: store-web
    build:
      context: store-web
    ports:
      - "3000:3000"

  store-nginx:
    image: toy-store-nginx:0.0.1
    container_name: store-nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - store-service
      - store-web
    ports:
      - "80:80"
