apiVersion: v1
kind: Service
metadata:
  name: bank-gateway
spec: 
  type: NodePort
  selector:
    app: bank-gateway
  ports: 
    - protocol: TCP
      port: 8882
      targetPort: 8882
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bank-gateway
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: bank-gateway
  template:
    metadata: 
      labels: 
        app: bank-gateway
    spec:
      restartPolicy: Always
      containers:
      - image: toy-store-bankgateway:0.0.1
        name:  bank-gateway
        ports:
        - containerPort: 8882
        
