apiVersion: extentions/v1beta1
kind: Deployment
metadata: 
  name: store-service
spec: 
  replicas: 1
  template:
    metadata: 
      labels: 
        app: store-service
    spec:
      restartPolicy: Always
      
